#!/usr/bin/env bash
# =============================================================================
#  backup-apps.sh — snapshot the installed software of this Mac
# =============================================================================
#  Run on the OLD Mac. Produces, next to this script:
#     Brewfile        — everything Homebrew knows (taps, formulae, casks,
#                       App Store apps via mas, VS Code extensions)
#     manual-apps.md  — apps in /Applications that Homebrew does NOT manage
#                       and that did not come from the App Store → you have to
#                       reinstall these manually (vendor download).
#
#  USAGE:
#     chmod +x backup-apps.sh
#     ./backup-apps.sh
# =============================================================================

set -uo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BREWFILE="$SCRIPT_DIR/Brewfile"
MANUAL="$SCRIPT_DIR/manual-apps.md"

c_reset=$'\033[0m'; c_b=$'\033[1m'; c_g=$'\033[32m'; c_y=$'\033[33m'; c_r=$'\033[31m'; c_c=$'\033[36m'
say(){ printf '%s\n' "$*"; }
have(){ command -v "$1" >/dev/null 2>&1; }
have brew || { say "${c_r}brew missing — install Homebrew first (https://brew.sh).${c_reset}"; exit 1; }

say "${c_b}${c_c}Snapshotting installed software → $BREWFILE${c_reset}"

# --- 1) Brewfile dump ---------------------------------------------------------
# --vscode also dumps VS Code extensions; older brew versions don't have the
# flag, so fall back to a plain dump.
if brew bundle dump --file="$BREWFILE" --force --vscode 2>/dev/null; then
  say "  ${c_g}✓ Brewfile written (incl. VS Code extensions)${c_reset}"
elif brew bundle dump --file="$BREWFILE" --force; then
  say "  ${c_g}✓ Brewfile written (without --vscode, flag unsupported)${c_reset}"
else
  say "  ${c_r}✗ brew bundle dump failed${c_reset}"; exit 1
fi
say "     $(grep -c '^tap '  "$BREWFILE" 2>/dev/null || echo 0) taps, \
$(grep -c '^brew ' "$BREWFILE" 2>/dev/null || echo 0) formulae, \
$(grep -c '^cask ' "$BREWFILE" 2>/dev/null || echo 0) casks, \
$(grep -c '^mas '  "$BREWFILE" 2>/dev/null || echo 0) mas apps"

# --- 2) manual-apps.md — apps Homebrew does not manage ------------------------
# HEURISTIC: an app in /Applications counts as "manual" if
#   • it has no _MASReceipt (i.e. it did not come from the App Store), AND
#   • its name does not match any installed cask token (name lowercased,
#     spaces → dashes), AND it is not a symlink into the Caskroom.
# Cask tokens do not always match app names 1:1, so review the list — some
# entries may still be brew-managed under a different token.
say "${c_b}${c_c}Detecting manually installed apps → $MANUAL${c_reset}"
CASKS="$(brew list --cask 2>/dev/null || true)"
CASKROOM="$(brew --caskroom 2>/dev/null || echo /opt/homebrew/Caskroom)"

{
  echo "# Manually installed apps"
  echo ""
  echo "Generated by backup-apps.sh on $(date '+%Y-%m-%d %H:%M')."
  echo "These apps are neither Homebrew casks nor App Store apps (heuristic —"
  echo "double-check before relying on it). Reinstall them via vendor download:"
  echo ""
} > "$MANUAL"

count=0
shopt -s nullglob
for app in /Applications/*.app; do
  name="$(basename "$app" .app)"
  # App Store apps carry a receipt — restored via mas / App Store sign-in
  [ -e "$app/Contents/_MASReceipt" ] && continue
  # symlink into the Caskroom → clearly brew-managed
  if [ -L "$app" ] && [[ "$(readlink "$app")" == *"$CASKROOM"* ]]; then continue; fi
  # name matches an installed cask token → assume brew-managed
  slug="$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
  if [ -n "$CASKS" ] && printf '%s\n' "$CASKS" | grep -qixF -- "$slug"; then continue; fi
  echo "- **$name** (\`$app\`)" >> "$MANUAL"
  say "  + $name"
  count=$((count+1))
done
shopt -u nullglob
[ "$count" -eq 0 ] && echo "_None found — everything is managed by Homebrew or the App Store._" >> "$MANUAL"
say "  ${c_g}✓ $count manual app(s) → $MANUAL${c_reset}"

say ""
say "${c_g}${c_b}Done.${c_reset}"
say "${c_y}➜ Next: ./backup-secrets.sh and ./backup-browser-profiles.sh, then ./verify-backups.sh${c_reset}"
say "➜ On the new Mac, restore.sh consumes this Brewfile."
